### ISSUE TITLE
opps

### ISSUE THREAD

**Issue by sably** [wildcatco/notion-blog#1]
when I navigate between routes and go to /blog route then:

![Screenshot 2023-06-01 123905](https://github.com/wildcatco/notion-blog/assets/25221341/8880f7aa-5bea-4c38-8f21-1555293802c3)
 why?

**Comment by wildcatco** [comment]
Make sure you set your evironment variables correctly.
Try console log process.env.NOTION_DATABASE_ID in that function.

**Comment by sably** [comment]
ty, I set that but still a problem:

![Screenshot 2023-06-01 140403](https://github.com/wildcatco/notion-blog/assets/25221341/efb285dc-b123-4c8d-8641-82b0130214d5)
![Screenshot 2023-06-01 140002](https://github.com/wildcatco/notion-blog/assets/25221341/606df118-2d11-4874-a802-2387b7a10683)

**Comment by sably** [comment]
and what is process.env.NOTION_AUTH_TOKEN?

**Comment by wildcatco** [comment]
Please read getting started part in readme.
If you get an error after setting all the environment variables, let me know again.

**Comment by sably** [comment]
ty so much, it works fine, but the images r not loaded:
![ssssssss](https://github.com/wildcatco/notion-blog/assets/25221341/2fe582b9-7a45-4d60-8938-bc359192f78b)

🥰

**Comment by sably** [comment]
but their links work properly, when I open them separately: 

![fffffffffffffffffff](https://github.com/wildcatco/notion-blog/assets/25221341/11b16bc9-e176-4d2e-beb6-595568d22ca2)

**Comment by wildcatco** [comment]
Make sure your notion page is public (stated in step 1 in getting started)
<img src="https://www.notion.so/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2Fspoqsaf9291f%2F6rV4r5KUjT12cIfAdaGXW%2F1cf59dda0f64b2c8f6c6106cc64883a6%2FPublic_Share_to_the_Web.png&w=3840&q=100"/>

**Comment by sably** [comment]
It's ridicules, solved by checking some options:

![Screenshot 2023-06-01 173219](https://github.com/wildcatco/notion-blog/assets/25221341/b9f3b94f-1ab8-42d4-9287-48d0cb26f006)

**Comment by sably** [comment]
btw ty for ur help, love u much

**Comment by wildcatco** [comment]
Glad you fix the problem, but i think you shoud not allow others to edit your page.

**Comment by ShivamBunge** [comment]
Thank you for the answers. It was helplful. One more question - Can this app be used for large scale apps like apps having some 1000 blogs and what about the security aspects? @wildcatco

**Comment by wildcatco** [comment]
@ShivamBunge 
This project uses notion-client from this [repo](https://github.com/NotionX/react-notion-x).
Because notion-client has rate limit, build time may be long. And updating too many posts may take long time.
I don't see any security issue.
