### ISSUE TITLE
display only published articles in the related posts

### ISSUE THREAD

**Issue by yutakusuno** [wildcatco/notion-blog#4]
hello, i really appreciate your great work

i have a question though
constant `relatedPosts` is the intended implementation?
see: [src/app/blog/[slug]/page.tsx: 38](https://github.com/wildcatco/notion-blog/blob/main/src/app/blog/%5Bslug%5D/page.tsx#L39)

```
  const relatedPosts: Post[] = allPosts.filter(
    (p) =>
      p.slug !== slug && p.categories.some((v) => post.categories.includes(v))
  );
```

is the following a better way to display only published articles in the related posts?

```
  const relatedPosts: Post[] = allPosts.filter(
    (p) =>
      p.slug !== slug &&
      p.published &&
      p.categories.some((v) => post.categories.includes(v))
  );
```

**Comment by wildcatco** [comment]
@yutakusuno You are right! I missed that point. 
Would you mind creating a pull request for that? Thank you for finding the bug😀
