### ISSUE TITLE
Wrong password when deploy to vercel

### ISSUE THREAD

**Issue by mpquochung** [wildcatco/notion-blog#7]
![image](https://github.com/wildcatco/notion-blog/assets/107011469/37bf00c8-0112-42f7-84ad-502da2508d78)
I typed in password in the .env, and it is correct in local host
But when deploy to Vercel, the password is incorrect:
![image](https://github.com/wildcatco/notion-blog/assets/107011469/5a28b719-2d9b-47c3-bbef-8dab180f80eb)

**Comment by wildcatco** [comment]
When deploying with vercel, you have to set environment variables in project settings.
![스크린샷 2024-01-10 141728](https://github.com/wildcatco/notion-blog/assets/53351097/95259a84-53a4-4bdd-9bf5-2ca994938e69)


https://vercel.com/docs/projects/environment-variables
